#!/bin/bash

declare -g HISTFN=~/.surf/onmibar-history
declare -g NITEMS=5

urlencode() {
	printf %s "$1" | od -t x1 -An | tr -d '\n' | tr ' ' '%'
}

trim() {
	echo "$1" | sed 's/^[ ]*//;s/[ ]*$//'
}

addhist() {
	[ -z "$1" ] && return

	local -r u="$1"
	local n="$(sed -n "s|^\([0-9]*\) ${u}$|\1|p" "$HISTFN")"

	if [ -z "$n" ]; then
		echo "1 ${u}" >> "$HISTFN"
	else
		n="$(echo $n+1|bc)"
		un="$(echo "$u" |sed 's/&/\\&/g')"
		sed -i "s|^\([0-9]*\) ${u}$|${n} ${un}|" "$HISTFN"
	fi
}

geturi() {
	local -r s="$1"
	local -r host="$(echo "$s" | sed 's,^\(.*://\|\)\([^/:]*\).*,\2,')"
	local -r scheme="$(echo "$s" |cut -sd: -f1)"
	local -r searchengine="$(echo "$s" |cut -sd' ' -f1)"
	local search uri searchquery
	# search only when no scheme or it's http(s)
	if [ "$scheme" = "http" -o "$scheme" = "https" ]; then
		search=0
	else
		search="$(nc --zero --wait 1 "$host" 80 2> /dev/null; echo $?)"
	fi

	if [ "$search" -ne 0 ]; then
		case "$searchengine" in
			hg)
				uri="https://hoogle.haskell.org/?hoogle="
				searchquery="${s:2}"
				;;
			g)
				uri="http://www.google.com/search?q="
				searchquery="${s:1}"
				;;
			s)
				uri="https://startpage.com/do/dsearch?query="
				searchquery="${s:1}"
				;;
			ddg)
				uri="https://duckduckgo.com/?q="
				searchquery="${s:3}"
				;;
			*)
				uri="https://startpage.com/do/dsearch?query="
				searchquery="$s"
				;;
		esac
		# enjoy !bangs
		uri+="$(urlencode "$searchquery")"
	else
		uri="$s"
	fi
	echo "$uri"
}

goto() {
	local -r xid="$1"
	local -r prop="$2"
	local uri s

	s="$(cat "$HISTFN" |sort -rn | cut -d' ' -f2- | dmenu -i -l "$NITEMS" -w "$xid")"
	s="$(trim "$s")"
	[ -z "$s" ] && return

	addhist "$s"
	uri="$(geturi "$s")"

	[ -z "$xid" -o -z "$prop" -o -z "$uri" ] && exit 1
	xprop -id "$xid" -f "$prop" 8s -set "$prop" "$uri"
}

main() {
	local -r cmd="$1"
	shift
	$cmd "$@"
}

main "$@"
